package com.ericneidhardt.dynamicsoundboard.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEDIA_PLAYER_DATA.
 */
public class MediaPlayerData {

    private Long id;
    private String playerId;
    private String fragmentTag;
    private String label;
    private String uri;

    public MediaPlayerData() {
    }

    public MediaPlayerData(Long id) {
        this.id = id;
    }

    public MediaPlayerData(Long id, String playerId, String fragmentTag, String label, String uri) {
        this.id = id;
        this.playerId = playerId;
        this.fragmentTag = fragmentTag;
        this.label = label;
        this.uri = uri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPlayerId() {
        return playerId;
    }

    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    public String getFragmentTag() {
        return fragmentTag;
    }

    public void setFragmentTag(String fragmentTag) {
        this.fragmentTag = fragmentTag;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

}
