package com.ericneidhardt.dynamicsoundboard.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEDIA_PLAYER_DATA.
 */
public class MediaPlayerData {

    private Long id;
    private String hash;

    public MediaPlayerData() {
    }

    public MediaPlayerData(Long id) {
        this.id = id;
    }

    public MediaPlayerData(Long id, String hash) {
        this.id = id;
        this.hash = hash;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

}
