package org.neidhardt.dynamicsoundboard.dao;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mediaPlayerDataDaoConfig;
    private final DaoConfig soundSheetDaoConfig;
    private final DaoConfig soundLayoutDaoConfig;

    private final MediaPlayerDataDao mediaPlayerDataDao;
    private final SoundSheetDao soundSheetDao;
    private final SoundLayoutDao soundLayoutDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mediaPlayerDataDaoConfig = daoConfigMap.get(MediaPlayerDataDao.class).clone();
        mediaPlayerDataDaoConfig.initIdentityScope(type);

        soundSheetDaoConfig = daoConfigMap.get(SoundSheetDao.class).clone();
        soundSheetDaoConfig.initIdentityScope(type);

        soundLayoutDaoConfig = daoConfigMap.get(SoundLayoutDao.class).clone();
        soundLayoutDaoConfig.initIdentityScope(type);

        mediaPlayerDataDao = new MediaPlayerDataDao(mediaPlayerDataDaoConfig, this);
        soundSheetDao = new SoundSheetDao(soundSheetDaoConfig, this);
        soundLayoutDao = new SoundLayoutDao(soundLayoutDaoConfig, this);

        registerDao(MediaPlayerData.class, mediaPlayerDataDao);
        registerDao(SoundSheet.class, soundSheetDao);
        registerDao(SoundLayout.class, soundLayoutDao);
    }
    
    public void clear() {
        mediaPlayerDataDaoConfig.getIdentityScope().clear();
        soundSheetDaoConfig.getIdentityScope().clear();
        soundLayoutDaoConfig.getIdentityScope().clear();
    }

    public MediaPlayerDataDao getMediaPlayerDataDao() {
        return mediaPlayerDataDao;
    }

    public SoundSheetDao getSoundSheetDao() {
        return soundSheetDao;
    }

    public SoundLayoutDao getSoundLayoutDao() {
        return soundLayoutDao;
    }

}
