package org.neidhardt.dynamicsoundboard.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.net.Uri;
import org.neidhardt.dynamicsoundboard.DynamicSoundboardApplication;
import org.neidhardt.dynamicsoundboard.daohelper.DaoHelperKt;
// KEEP INCLUDES END

/**
 * Entity mapped to table "MEDIA_PLAYER_DATA".
 */
@Entity
public class MediaPlayerData {

    @Id
    private Long id;

    @NotNull
    @Unique
    private String playerId;

    @NotNull
    private String fragmentTag;

    @NotNull
    private String label;

    @NotNull
    private String uri;
    private boolean isLoop;
    private boolean isInPlaylist;
    private Long timePosition;
    private Integer sortOrder;

    @Transient
    private boolean isSelectedForDeletion;

    @Generated(hash = 191052172)
    public MediaPlayerData() {
    }

    public MediaPlayerData(Long id) {
        this.id = id;
    }

    @Generated(hash = 1109844371)
    public MediaPlayerData(Long id, @NotNull String playerId, @NotNull String fragmentTag, @NotNull String label, @NotNull String uri, boolean isLoop, boolean isInPlaylist,
            Long timePosition, Integer sortOrder) {
        this.id = id;
        this.playerId = playerId;
        this.fragmentTag = fragmentTag;
        this.label = label;
        this.uri = uri;
        this.isLoop = isLoop;
        this.isInPlaylist = isInPlaylist;
        this.timePosition = timePosition;
        this.sortOrder = sortOrder;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getPlayerId() {
        return playerId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlayerId(@NotNull String playerId) {
        this.playerId = playerId;
    }

    @NotNull
    public String getFragmentTag() {
        return fragmentTag;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFragmentTag(@NotNull String fragmentTag) {
        this.fragmentTag = fragmentTag;
    }

    @NotNull
    public String getLabel() {
        return label;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLabel(@NotNull String label) {
        this.label = label;
    }

    @NotNull
    public String getUri() {
        return uri;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUri(@NotNull String uri) {
        this.uri = uri;
    }

    public boolean getIsLoop() {
        return isLoop;
    }

    public void setIsLoop(boolean isLoop) {
        this.isLoop = isLoop;
    }

    public boolean getIsInPlaylist() {
        return isInPlaylist;
    }

    public void setIsInPlaylist(boolean isInPlaylist) {
        this.isInPlaylist = isInPlaylist;
    }

    public Long getTimePosition() {
        return timePosition;
    }

    public void setTimePosition(Long timePosition) {
        this.timePosition = timePosition;
    }

    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    // KEEP METHODS - put your custom methods here

	public static MediaPlayerData getNewMediaPlayerData(String fragmentTag, Uri uri, String label)
	{
		MediaPlayerData data = new MediaPlayerData();

		data.playerId = Integer.toString((uri.toString() + DynamicSoundboardApplication.Companion.getRandomNumber()).hashCode());
		data.fragmentTag = fragmentTag;
		data.label = label;
		data.uri = uri.toString();
		data.isInPlaylist = false;
		data.isLoop = false;

		return data;
	}

	public void insertItemInDatabaseAsync()
	{
        DaoHelperKt.insertAsync(this).subscribe();
	}

    public void updateItemInDatabaseAsync()
	{
        DaoHelperKt.updateAsync(this).subscribe();
    }

    public boolean getIsSelectedForDeletion() {
        return isSelectedForDeletion;
    }

    public void setIsSelectedForDeletion(boolean isSelectedForDeletion) {
        this.isSelectedForDeletion = isSelectedForDeletion;
    }

    @Override
    public String toString() {
        return "MediaPlayerData{" +
                "id=" + id +
                ", playerId='" + playerId + '\'' +
                ", fragmentTag='" + fragmentTag + '\'' +
                ", label='" + label + '\'' +
                ", uri='" + uri + '\'' +
                ", isLoop=" + isLoop +
                ", isInPlaylist=" + isInPlaylist +
                ", timePosition=" + timePosition +
                ", sortOrder=" + sortOrder +
                '}';
    }
    // KEEP METHODS END

}
