package org.neidhardt.dynamicsoundboard.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SOUND_LAYOUT.
 */
public class SoundLayout {

    private Long id;
    private String label;
    private String databaseId;

    public SoundLayout() {
    }

    public SoundLayout(Long id) {
        this.id = id;
    }

    public SoundLayout(Long id, String label, String databaseId) {
        this.id = id;
        this.label = label;
        this.databaseId = databaseId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getDatabaseId() {
        return databaseId;
    }

    public void setDatabaseId(String databaseId) {
        this.databaseId = databaseId;
    }

}
